In [2]:
# as usual we should import the package
# This gives Python access to all of TensorFlow's classes, 
# methods, and symbols.
# in this sample we will solve a linear regression problem
# using the tensorflow

import tensorflow as tf

In [3]:
# In machine learning we will typically want a model that can take arbitrary inputs, 
# to make the model trainable, we need to be able to modify the graph to get new outputs 
# with the same input. Variables allow us to add trainable parameters to a graph. 
# They are constructed with a type and initial value:

with tf.variable_scope("my_scope"):
    W = tf.Variable([.3], dtype=tf.float32)
    b = tf.Variable([-.3], dtype=tf.float32)

x = tf.placeholder(tf.float32)

linear_model = W*x + b

In [4]:
# Constants are initialized when you call tf.constant, and their value can never change. 
# By contrast, variables are not initialized when you call tf.Variable. To initialize all 
# the variables in a TensorFlow program, you must explicitly call a special operation as follows:

sess = tf.Session()

init = tf.global_variables_initializer()
sess.run(init)

In [5]:
# It is important to realize init is a handle to the TensorFlow sub-graph that initializes 
# all the global variables. Until we call sess.run, the variables are uninitialized.

# Since x is a placeholder, we can evaluate linear_model for several 
# values of x simultaneously as follows:

print(sess.run(linear_model, {x: [1, 2, 3, 4]}))

for i in tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES, scope='my_scope'):
    print (i.initial_value) 

[ 0.          0.30000001  0.60000002  0.90000004]
Tensor("my_scope/Variable/initial_value:0", shape=(1,), dtype=float32)
Tensor("my_scope/Variable_1/initial_value:0", shape=(1,), dtype=float32)


In [6]:
# We've created a model, but we don't know how good it is yet. To evaluate the model 
# on training data, we need a y placeholder to provide the desired values, and we 
# need to write a loss function.

# A loss function measures how far apart the current model is from the provided data. 
# We'll use a standard loss model for linear regression, which sums the squares of 
# the deltas between the current model and the provided data. 
# linear_model - y creates a vector where each element is the corresponding example's 
# error delta. We call tf.square to square that error. Then, we sum all the squared 
# errors to create a single scalar that abstracts the error of all examples 
# using tf.reduce_sum:
# producing the loss value

y = tf.placeholder(tf.float32)
squared_deltas = tf.square(linear_model - y)
loss = tf.reduce_sum(squared_deltas)
print(sess.run(loss, {x: [1, 2, 3, 4], y: [0, -1, -2, -3]}))

23.66


In [17]:
# a simple adding model
# with two variables

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)

my_model = a + b;

session = tf.Session()

init = tf.global_variables_initializer()
session.run(init)

print(session.run(my_model, {a: [1,2,3,4], b: [3,4,5,6]}))
print(session.run(my_model, {a: [1], b: [3,2,5,6]}))

red_sum = tf.reduce_sum(b - a)

print(sess.run(red_sum, {a: [1, 2, 3, 4], b: [0, -1, -2, -3]}))

[ 4  6  8 10]
[4 3 6 7]
-16
